### ISSUE TITLE
gwyddion 2.53 does not compile with gcc 9

### ISSUE THREAD

**Issue by jborme** [istitov/stuff#110]
Copmilation issue with gcc 9.1.0-r1:
```gwyexpr.c: In function ‘gwy_expr_stack_interpret_vectors’:
gwyexpr.c:446:43: error: ‘call_table’ not specified in enclosing ‘parallel’
  446 |                     call_table[code->type].function(&sp);
      |                     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

Possible hack:

```diff -Naur gwyddion-2.53/libgwyddion/gwyexpr.c gwyddion-2.53_new/libgwyddion/gwyexpr.c
--- gwyddion-2.53/libgwyddion/gwyexpr.c 2019-06-09 13:10:31.634079402 +0100
+++ gwyddion-2.53_new/libgwyddion/gwyexpr.c     2019-06-09 13:12:40.588083959 +0100
@@ -427,7 +427,7 @@
 {
 #ifdef _OPENMP
 #pragma omp parallel if(gwy_threads_are_enabled()) default(none) \
-            shared(expr,n,data,result)
+            shared(expr,n,data,result,call_table)
 #endif
     {
         gdouble *stack = gwy_omp_if_threads_new(expr->stack, expr->slen);
```

**Comment by istitov** [comment]
Confirming, that it doesn't build with gcc:9.1.0...
If it compiles, does it work with this hack?

**Comment by jborme** [comment]
It does but only with gcc 9, according to upstream (they published the same patch some months ago, see below). Maybe could be applied selectively using testing gcc-major-version.

http://gwyddion.net/download.php#patches
gwyddion-2.53-gcc9-openmp-shared-const.patch | 2019-02-28 | 476 B
> Fixes a build failure with GCC 9.  Warning: It breaks compilation with other GCC versions.

**Comment by istitov** [comment]
@jborme , thanks for pointing out the patch, will change ebuild in today...

**Comment by istitov** [comment]
gwyddion is 2.54 now.
